# Generated by Django 5.0 on 2023-12-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('brand', models.CharField(max_length=50, verbose_name='Бренд')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Фото')),
                ('public_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
            ],
        ),
    ]
